_BASE_: dm12_cross_valley-3-500_maskformer2_R50_bs16_160k.yaml
DATASETS:
  TRAIN: ("dm12_cross_valley-3-500_clip_fix_box-single_p1500_prob",)
INPUT:
  DATASET_MAPPER_NAME: "mask_former_semantic2"
MODEL:
  UPDATE_TARGET: True
  TGT_UPDATE_WARMUP: 16 * 5000
  DYNAMIC_DESERT: False
  IOU_THRESHOLD: 0.1